
pool:
  name: MahlzeitExpress

variables:
  - group: DBAccess

jobs:
- job: SecureDemo
  displayName: "Secrets & Secure Files sicher verwenden"
  steps:

    - task: DownloadSecureFile@1
      name: fetchCert
      inputs:
        secureFile: dev.azure.com.pem
      displayName: "Secure File herunterladen (dev.azure.com.pem)"

    - bash: |
        echo "▶ Nutzername (sichtbar im Log): $(dbUsername)"
        echo "▶ Passwort (ausgeblendet): $(dbPassword)"
      displayName: "Secrets anzeigen (Demo-Ausgabe)"

    - bash: |
        echo "Speicherort des Secure Files:"
        echo "$(fetchCert.secureFilePath)"
        echo "Achtung: Datei wird nach dem Job automatisch gelöscht."
      displayName: "Speicherort des Secure Files anzeigen"

    - bash: |
        echo "Sicheres File entfernen (optional)"
        rm -f "$(fetchCert.secureFilePath)"
      displayName: "Manuelles Clean-up (nur optional)"
