trigger:
  branches:
    include: [ main ]

pool:
  name: MahlzeitExpress

stages:
- stage: Vorbereitung
  displayName: "🔧 Tools vorbereiten"
  jobs:
  - template: templates/install-tools.yml
    parameters:
      tools:
        - curl
        - jq
        - git
        - yamllint

- stage: Lint
  displayName: "🧹 YAML prüfen"
  dependsOn: Vorbereitung
  jobs:
  - template: templates/yaml-linter.yml
