trigger:
  branches:
    include:
      - main
  paths:
    include:
      - artifacts/SimpleLib/src/**
pool:
  name: MahlzeitExpress

variables:
  buildConfiguration: 'Release'
  projectPath: 'artifacts/SimpleLib/src/MahlzeitExpress/MahlzeitExpress.csproj'
  outputDir: 'nupkgs'
  feedUrl: 'https://pkgs.dev.azure.com/heiseacademy-azuredevops/MahlzeitExpress/_packaging/MahlzeitExpress/nuget/v3/index.json'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.0.x'

- task: NuGetAuthenticate@1
  displayName: 'Authenticate with Azure Artifacts'

- script: dotnet restore $(projectPath)
  displayName: 'Restore packages'

- script: dotnet build $(projectPath) --configuration $(buildConfiguration)
  displayName: 'Build project'

- script: dotnet pack $(projectPath) --configuration $(buildConfiguration) --output $(outputDir)
  displayName: 'Pack NuGet'

- script: |
    PACKAGE_NAME=$(ls $(outputDir)/*.nupkg | head -n 1)
    echo "Gefundenes Paket: $PACKAGE_NAME"
    dotnet nuget push "$PACKAGE_NAME" --source "$(feedUrl)" --api-key AzureDevOps
  displayName: 'Push to Azure Artifacts'
